### ISSUE TITLE
Python: user assertions without messages are too silent

### ISSUE THREAD

**Issue by Expurple** [codewars/python-test-framework#24]
When solution contains an `assert` statement (simple form, without a message) and that `assert` fails, tests are aborted without any error messages at all. It's hard to understand what's going on.

To reproduce: train on any Python kata, submit a function with `assert False` in its body. Compare with `assert False, "User assertion failed"`.

I'm not sure what can/should be done here, but it just felt very confusing, I had to debug my solution locally. I often add `assert`s to find bugs early. Without messages, of course. Initially I expected a full traceback, like from `raise RuntimeError()`. That would be very useful for debugging without a local IDE. But it looks like `AssertionError` is used by the test framework, so it's displayed differently.

**Comment by Blind4Basics** [comment]
same as #13, isn't it?
